# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Curfew < Formula
  desc "A local-first terminal curfew for risky commands during quiet hours"
  homepage "https://github.com/iamrajjoshi/curfew"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/iamrajjoshi/curfew/releases/download/v0.1.0/curfew_darwin_amd64.tar.gz"
      sha256 "f0c020e55f978d110a822df255f96d8f5f8baa336d5b1e83d349394d4ee0d622"

      define_method(:install) do
        bin.install "curfew"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/iamrajjoshi/curfew/releases/download/v0.1.0/curfew_darwin_arm64.tar.gz"
      sha256 "573e97e479344d8182ecdf45e8ba675daa9d757b62f91c7da14a7da476a49e98"

      define_method(:install) do
        bin.install "curfew"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/iamrajjoshi/curfew/releases/download/v0.1.0/curfew_linux_amd64.tar.gz"
      sha256 "e6568a3dd2a6ddbaa765fb8b6265891a46b14d13b942a83bba585b2d0cd45b00"
      define_method(:install) do
        bin.install "curfew"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/iamrajjoshi/curfew/releases/download/v0.1.0/curfew_linux_arm64.tar.gz"
      sha256 "92854dfbc76e5f66a19a74594e88ab8bab41474a8702cab1447dbd672dec55af"
      define_method(:install) do
        bin.install "curfew"
      end
    end
  end

  test do
    system bin/"curfew", "version"
  end
end
