# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Willow < Formula
  desc "A simple, opinionated git worktree manager"
  homepage "https://github.com/iamrajjoshi/willow"
  version "0.6.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/iamrajjoshi/willow/releases/download/v0.6.3/willow_darwin_amd64.tar.gz"
      sha256 "51751553872bcdc437e9b31eb1a3ba1ee327803b7739dba81f51c2cbea33a5cd"

      define_method(:install) do
        bin.install "willow"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/iamrajjoshi/willow/releases/download/v0.6.3/willow_darwin_arm64.tar.gz"
      sha256 "90b93950d1080a16065b40d5de4b7a2464c44cb03adc96b35280c8047d75abf6"

      define_method(:install) do
        bin.install "willow"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/iamrajjoshi/willow/releases/download/v0.6.3/willow_linux_amd64.tar.gz"
      sha256 "ef6ab754bd729a01c111a70c2632944440c3e0500e4f3f1d05f9b3e67f2d0f96"
      define_method(:install) do
        bin.install "willow"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/iamrajjoshi/willow/releases/download/v0.6.3/willow_linux_arm64.tar.gz"
      sha256 "a4bfcf4cbe50495e15a6351e47c8d2168caf41c4f7ca2c37b4a1e3c25ca0f15e"
      define_method(:install) do
        bin.install "willow"
      end
    end
  end

  test do
    system bin/"willow", "--version"
  end
end
