# This file was generated by GoReleaser. DO NOT EDIT.
cask "willow" do
  name "willow"
  desc "A simple, opinionated git worktree manager"
  homepage "https://github.com/iamrajjoshi/willow"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "willow"

  on_macos do
    on_intel do
      url "https://github.com/iamrajjoshi/willow/releases/download/v#{version}/willow_darwin_amd64.tar.gz"
      sha256 "154022889cf31e8b0e5c43c4b5c6696364e9646d08e45aa9766106a916a1e6e0"
    end
    on_arm do
      url "https://github.com/iamrajjoshi/willow/releases/download/v#{version}/willow_darwin_arm64.tar.gz"
      sha256 "73ee97ebdee8e8ab7e325f04e7cb86836389289c2b9530a6f430d3d4eb27c016"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/iamrajjoshi/willow/releases/download/v#{version}/willow_linux_amd64.tar.gz"
      sha256 "82c7aa3d7780de0efaa6231df48942bd4d5c5808234f24487d2feee15e4ff131"
    end
    on_arm do
      url "https://github.com/iamrajjoshi/willow/releases/download/v#{version}/willow_linux_arm64.tar.gz"
      sha256 "7e7396a9eed7500d845106fa160334ff756c61027fb20ecd5f263d4c66a040ee"
    end
  end

  # No zap stanza required
end
