# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Willow < Formula
  desc "A simple, opinionated git worktree manager"
  homepage "https://github.com/iamrajjoshi/willow"
  version "3.0.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/iamrajjoshi/willow/releases/download/v3.0.4/willow_darwin_amd64.tar.gz"
      sha256 "e7386c63a6d0222930a0cf000df793f2069b3a56920ddc23583fdc67dacb8fab"

      define_method(:install) do
        bin.install "willow"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/iamrajjoshi/willow/releases/download/v3.0.4/willow_darwin_arm64.tar.gz"
      sha256 "f363976a41c2b9295df55f08e54979a2abe2f5be220b91993ccb0108aa83353f"

      define_method(:install) do
        bin.install "willow"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/iamrajjoshi/willow/releases/download/v3.0.4/willow_linux_amd64.tar.gz"
      sha256 "30a5400a994ae290597a22ba1463eacdac79ff922aa297c07cf957b9577160a8"
      define_method(:install) do
        bin.install "willow"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/iamrajjoshi/willow/releases/download/v3.0.4/willow_linux_arm64.tar.gz"
      sha256 "965a8ab4c0ab756f578b96c0430283e102428689356a0a1eddd13f3104410ee1"
      define_method(:install) do
        bin.install "willow"
      end
    end
  end

  test do
    system bin/"willow", "--version"
  end
end
